FROM dylangmiles/docker-moodle-phpfpm:php-7.1

MAINTAINER "Dylan Miles" <dylan.g.miles@gmail.com>

# Configure XDebug
#RUN   echo "xdebug.remote_enable = 1" >> /etc/php5/fpm/conf.d/20-xdebug.ini
#RUN   echo "xdebug.remote_connect_back = 1" >> /etc/php5/fpm/conf.d/20-xdebug.ini
#RUN   echo "xdebug.remote_port = 9000" >> /etc/php5/fpm/conf.d/20-xdebug.ini

#RUN mkdir -p /data
#VOLUME ["/data"]

#EXPOSE 9000

#ENTRYPOINT ["/usr/sbin/php5-fpm", "-F"]
